HotDogReview.WebUI/Controllers/EstablishmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HotDogReview.Core.Geocoding;
using HotDogReview.WebUI.Models;
using HotDogReview.WebUI.ViewModels;

namespace HotDogReview.WebUI.Controllers
{
    public class EstablishmentsController : Controller
    {
        // Fields.
        private HotDogReviewEntities db = new HotDogReviewEntities();

        // Actions.
        public ActionResult Index()
        {
            return View(db.Establishments.ToList());
        }
        public ActionResult Details(int id = 0)
        {
            Establishment establishment = db.Establishments.Find(id);
            if (establishment == null)
            {
                return HttpNotFound();
            }
            return View(establishment);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NewEstablishmentViewModel viewModel)
        {
            viewModel.Establishment.CreatedDateTime = DateTime.Now;

            // Geocodes the address.
            try
            {
                var geocoder = new GoogleGeocodingService();
                var coords = geocoder.GetCoordinate(viewModel.Establishment.Address);
				viewModel.Establishment.Latitude = coords.Latitude;
				viewModel.Establishment.Longitude = coords.Longitude;
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Não foi possível localizar o endereço. Detalhes: " + ex.Message);
            }

            if (ModelState.IsValid)
            {
				if (ExistsEstablishment(viewModel.Establishment.Name))
				{
					ModelState.AddModelError("", string.Format("O Estabelecimento \"{0}\" já está cadastrado", viewModel.Establishment.Name));
					return View(viewModel);
				}

                db.Establishments.Add(viewModel.Establishment);
                db.SaveChanges();

				viewModel.Review.EstablishmentId = viewModel.Establishment.Id;
				viewModel.Review.CreatedDateTime = DateTime.Now;

				db.Reviews.Add(viewModel.Review);
				db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

		private bool ExistsEstablishment(string name)
		{
			return db.Establishments.FirstOrDefault(entity => entity.Name.Equals(name.Trim(), StringComparison.InvariantCultureIgnoreCase)) != null;
		}

        public ActionResult Edit(int id = 0)
        {
            Establishment establishment = db.Establishments.Find(id);
            if (establishment == null)
            {
                return HttpNotFound();
            }
            return View(establishment);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Establishment establishment)
        {
            // Geocodes the address.
            try
            {
                var geocoder = new GoogleGeocodingService();
                var coords = geocoder.GetCoordinate(establishment.Address);
                establishment.Latitude = coords.Latitude;
                establishment.Longitude = coords.Longitude;
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Não foi possível localizar o endereço. Detalhes: " + ex.Message);
            }

            if (ModelState.IsValid)
            {
                db.Entry(establishment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(establishment);
        }
        public ActionResult Delete(int id = 0)
        {
            Establishment establishment = db.Establishments.Find(id);
            if (establishment == null)
            {
                return HttpNotFound();
            }
            return View(establishment);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Establishment establishment = db.Establishments.Find(id);
            db.Establishments.Remove(establishment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // IDisposable methods.
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

HotDogReview.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HotDogReview.WebUI.Models;

namespace HotDogReview.WebUI.Controllers
{
    public class HomeController : Controller
    {
        // Fields.
        private HotDogReviewEntities db = new HotDogReviewEntities();

        // Actions.
        public ActionResult Index()
        {
            var model = db.Establishments
                .Include("Reviews")
                .ToList();

            return View(model);
        }

        // IDisposable methods.
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

HotDogReview.WebUI/Controllers/ReviewsController.cs
using HotDogReview.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HotDogReview.WebUI.Controllers
{
    public class ReviewsController : Controller
    {
		// Fields.
		private HotDogReviewEntities db = new HotDogReviewEntities();

		// Actions.
        public ActionResult Index()
        {
            return View();
        }

		public ActionResult Create(int id)
		{
			Establishment establishment = db.Establishments.FirstOrDefault(entity => entity.Id == id);
			if (establishment == null)
				return RedirectToAction("Index", "Home");

			ViewBag.EstablishmentName = establishment.Name;
			Review review = new Review
			{
				EstablishmentId = id
			};

			return View(review);
		}
		[HttpPost]
		public ActionResult Create(Review review)
		{
			review.CreatedDateTime = DateTime.Now;

			if (ModelState.IsValid)
			{
				db.Reviews.Add(review);
				db.SaveChanges();

				return RedirectToAction("Index", "Home");
			}

			return View(review);
		}
    }
}

HotDogReview.WebUI/Views/Home/Index.cshtml
@model IEnumerable<HotDogReview.WebUI.Models.Establishment>

@{
    ViewBag.Title = "Hot Dog Review";
}

<img src="/Content/Images/dog.png" />

<h2>Barraquinhas de Dogão em Curitiba</h2>

<div id="map-canvas" style="width: 800px; height: 380px;"></div>

<p>
    <a href="@Url.Action("Create", "Establishments")">[+] Cadastrar barraquinha</a>
</p>

<ul>
    @foreach(var item in Model)
    {
        <li>
            <h4>@item.Name</h4>
            <p>
                Nota @item.AverageRating (@item.Reviews.Count() avaliações) | <a href="@Url.Action("Create", "Reviews", new { id=@item.Id })">Avaliar</a>
            </p>
            <p>
                Endereço: @(item.Address ?? "<sem endereço>")
            </p>
            <p>
                @(item.Description ?? "<sem descrição>")
            </p>
        </li>
    }
</ul>

<hr />

<script src="~/Scripts/jquery-1.8.2.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDNMP3K0GDuGhuhhDkXriZcIaL2DLMYD1M&sensor=false"></script>

<script>

    var HomeIndex = function () {

        var _map,
            _mapOverlays = [];

        function createMap() {
            _map = new google.maps.Map(document.getElementById("map-canvas"), {
                center: new google.maps.LatLng(-25.4166667, -49.25),
                zoom: 8,
                mapTypeId: google.maps.MapTypeId.ROADMAP });
        }

        function createMarker(index, resultItem) {
            var coords = new google.maps.LatLng(resultItem.lat, resultItem.lng);
            var marker = new google.maps.Marker({
                position: coords,
                title: resultItem.title + ' - ' + resultItem.averageRating });
            return marker;
        }

        function init() {
            createMap();
            setMarkers();
        }

        function setMarkers() {
            $.get('/Api/EstablishmentsApi/GetMarkers/', function (data) {
                _mapOverlays = [];
                $.each(data, function (index, item) {
                    var marker = createMarker(index, item);
                    marker.setMap(_map)
                    _mapOverlays.push(marker);
                });
                if (_mapOverlays.length) {
                    var bounds = new google.maps.LatLngBounds();
                    for (var i = 0; i < _mapOverlays.length; i++) {
                         bounds.extend(_mapOverlays[i].position);
                    }
                    _map.fitBounds(bounds);
                    var listener = google.maps.event.addListener(_map, "idle", function() { 
                        if (_map.getZoom() > 16) _map.setZoom(16); 
                        google.maps.event.removeListener(listener); 
                    });
                }
            });
        }

        return {
            init: init
        };

    } ();

    HomeIndex.init();

</script>